# Generated by Django 4.2 on 2023-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.IntegerField(default=2),
        ),
    ]
