# Generated by Django 4.2 on 2023-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.IntegerField(default=2, verbose_name='Poll owner'),
        ),
    ]
